bigday/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^', include('wedding.urls')),
    url(r'^', include('guests.urls')),
    url(r'^admin/', admin.site.urls),
    url('^accounts/', include('django.contrib.auth.urls'))
]

guests/urls.py
from django.conf.urls import url

from guests.views import GuestListView, test_email, save_the_date_preview, save_the_date_random, export_guests, \
    invitation, invitation_email_preview, invitation_email_test, rsvp_confirm, dashboard

urlpatterns = [
    url(r'^guests/$', GuestListView.as_view(), name='guest-list'),
    url(r'^dashboard/$', dashboard, name='dashboard'),
    url(r'^guests/export$', export_guests, name='export-guest-list'),
    url(r'^invite/(?P<invite_id>[\w-]+)/$', invitation, name='invitation'),
    url(r'^invite-email/(?P<invite_id>[\w-]+)/$', invitation_email_preview, name='invitation-email'),
    url(r'^invite-email-test/(?P<invite_id>[\w-]+)/$', invitation_email_test, name='invitation-email-test'),
    url(r'^save-the-date/$', save_the_date_random, name='save-the-date-random'),
    url(r'^save-the-date/(?P<template_id>[\w-]+)/$', save_the_date_preview, name='save-the-date'),
    url(r'^email-test/(?P<template_id>[\w-]+)/$', test_email, name='test-email'),
    url(r'^rsvp/confirm/(?P<invite_id>[\w-]+)/$', rsvp_confirm, name='rsvp-confirm'),
]

guests/models.py
from __future__ import unicode_literals
import datetime
import uuid

from django.db import models
from django.dispatch import receiver

# these will determine the default formality of correspondence
ALLOWED_TYPES = [
    ('formal', 'formal'),
    ('fun', 'fun'),
    ('dimagi', 'dimagi'),
]


def _random_uuid():
    return uuid.uuid4().hex


class Party(models.Model):
    """
    A party consists of one or more guests.
    """
    name = models.TextField()
    type = models.CharField(max_length=10, choices=ALLOWED_TYPES)
    category = models.CharField(max_length=20, null=True, blank=True)
    save_the_date_sent = models.DateTimeField(null=True, blank=True, default=None)
    save_the_date_opened = models.DateTimeField(null=True, blank=True, default=None)
    invitation_id = models.CharField(max_length=32, db_index=True, default=_random_uuid, unique=True)
    invitation_sent = models.DateTimeField(null=True, blank=True, default=None)
    invitation_opened = models.DateTimeField(null=True, blank=True, default=None)
    is_invited = models.BooleanField(default=False)
    rehearsal_dinner = models.BooleanField(default=False)
    is_attending = models.NullBooleanField(default=None)
    comments = models.TextField(null=True, blank=True)

    def __str__(self):
        return 'Party: {}'.format(self.name)

    @classmethod
    def in_default_order(cls):
        return cls.objects.order_by('category', '-is_invited', 'name')

    @property
    def ordered_guests(self):
        return self.guest_set.order_by('is_child', 'pk')

    @property
    def any_guests_attending(self):
        return any(self.guest_set.values_list('is_attending', flat=True))

    @property
    def guest_emails(self):
        return list(filter(None, self.guest_set.values_list('email', flat=True)))


MEALS = [
    ('beef', 'cow'),
    ('fish', 'fish'),
    ('hen', 'hen'),
    ('vegetarian', 'vegetable'),
]


class Guest(models.Model):
    """
    A single guest
    """
    party = models.ForeignKey('Party', on_delete=models.CASCADE)
    first_name = models.TextField()
    last_name = models.TextField(null=True, blank=True)
    email = models.TextField(null=True, blank=True)
    is_attending = models.NullBooleanField(default=None)
    meal = models.CharField(max_length=20, choices=MEALS, null=True, blank=True)
    is_child = models.BooleanField(default=False)

    @property
    def name(self):
        return u'{} {}'.format(self.first_name, self.last_name)

    @property
    def unique_id(self):
        # convert to string so it can be used in the "add" templatetag
        return str(self.pk)

    def __str__(self):
        return 'Guest: {} {}'.format(self.first_name, self.last_name)

guests/views.py
import base64
from collections import namedtuple
import random
from datetime import datetime
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.db.models import Count, Q
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.views.generic import ListView
from guests import csv_import
from guests.invitation import get_invitation_context, INVITATION_TEMPLATE, guess_party_by_invite_id_or_404, \
    send_invitation_email
from guests.models import Guest, MEALS, Party
from guests.save_the_date import get_save_the_date_context, send_save_the_date_email, SAVE_THE_DATE_TEMPLATE, \
    SAVE_THE_DATE_CONTEXT_MAP


class GuestListView(ListView):
    model = Guest


@login_required
def export_guests(request):
    export = csv_import.export_guests()
    response = HttpResponse(export.getvalue(), content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename=all-guests.csv'
    return response


@login_required
def dashboard(request):
    parties_with_pending_invites = Party.objects.filter(
        is_invited=True, is_attending=None
    ).order_by('category', 'name')
    parties_with_unopen_invites = parties_with_pending_invites.filter(invitation_opened=None)
    parties_with_open_unresponded_invites = parties_with_pending_invites.exclude(invitation_opened=None)
    attending_guests = Guest.objects.filter(is_attending=True)
    guests_without_meals = attending_guests.filter(
        is_child=False
    ).filter(
        Q(meal__isnull=True) | Q(meal='')
    ).order_by(
        'party__category', 'first_name'
    )
    meal_breakdown = attending_guests.exclude(meal=None).values('meal').annotate(count=Count('*'))
    category_breakdown = attending_guests.values('party__category').annotate(count=Count('*'))
    return render(request, 'guests/dashboard.html', context={
        'guests': Guest.objects.filter(is_attending=True).count(),
        'possible_guests': Guest.objects.filter(party__is_invited=True).exclude(is_attending=False).count(),
        'not_coming_guests': Guest.objects.filter(is_attending=False).count(),
        'pending_invites': parties_with_pending_invites.count(),
        'pending_guests': Guest.objects.filter(party__is_invited=True, is_attending=None).count(),
        'guests_without_meals': guests_without_meals,
        'parties_with_unopen_invites': parties_with_unopen_invites,
        'parties_with_open_unresponded_invites': parties_with_open_unresponded_invites,
        'unopened_invite_count': parties_with_unopen_invites.count(),
        'total_invites': Party.objects.filter(is_invited=True).count(),
        'meal_breakdown': meal_breakdown,
        'category_breakdown': category_breakdown,
    })


def invitation(request, invite_id):
    party = guess_party_by_invite_id_or_404(invite_id)
    if party.invitation_opened is None:
        # update if this is the first time the invitation was opened
        party.invitation_opened = datetime.utcnow()
        party.save()
    if request.method == 'POST':
        for response in _parse_invite_params(request.POST):
            guest = Guest.objects.get(pk=response.guest_pk)
            assert guest.party == party
            guest.is_attending = response.is_attending
            guest.meal = response.meal
            guest.save()
        if request.POST.get('comments'):
            comments = request.POST.get('comments')
            party.comments = comments if not party.comments else '{}; {}'.format(party.comments, comments)
        party.is_attending = party.any_guests_attending
        party.save()
        return HttpResponseRedirect(reverse('rsvp-confirm', args=[invite_id]))
    return render(request, template_name='guests/invitation.html', context={
        'party': party,
        'meals': MEALS,
    })


InviteResponse = namedtuple('InviteResponse', ['guest_pk', 'is_attending', 'meal'])


def _parse_invite_params(params):
    responses = {}
    for param, value in params.items():
        if param.startswith('attending'):
            pk = int(param.split('-')[-1])
            response = responses.get(pk, {})
            response['attending'] = True if value == 'yes' else False
            responses[pk] = response
        elif param.startswith('meal'):
            pk = int(param.split('-')[-1])
            response = responses.get(pk, {})
            response['meal'] = value
            responses[pk] = response

    for pk, response in responses.items():
        yield InviteResponse(pk, response['attending'], response.get('meal', None))


def rsvp_confirm(request, invite_id=None):
    party = guess_party_by_invite_id_or_404(invite_id)
    return render(request, template_name='guests/rsvp_confirmation.html', context={
        'party': party,
        'support_email': settings.DEFAULT_WEDDING_REPLY_EMAIL,
    })


@login_required
def invitation_email_preview(request, invite_id):
    party = guess_party_by_invite_id_or_404(invite_id)
    context = get_invitation_context(party)
    return render(request, INVITATION_TEMPLATE, context=context)


@login_required
def invitation_email_test(request, invite_id):
    party = guess_party_by_invite_id_or_404(invite_id)
    send_invitation_email(party, recipients=[settings.DEFAULT_WEDDING_TEST_EMAIL])
    return HttpResponse('sent!')


def save_the_date_random(request):
    template_id = random.choice(SAVE_THE_DATE_CONTEXT_MAP.keys())
    return save_the_date_preview(request, template_id)


def save_the_date_preview(request, template_id):
    context = get_save_the_date_context(template_id)
    context['email_mode'] = False
    return render(request, SAVE_THE_DATE_TEMPLATE, context=context)


@login_required
def test_email(request, template_id):
    context = get_save_the_date_context(template_id)
    send_save_the_date_email(context, [settings.DEFAULT_WEDDING_TEST_EMAIL])
    return HttpResponse('sent!')


def _base64_encode(filepath):
    with open(filepath, "rb") as image_file:
        return base64.b64encode(image_file.read())

guests/templates/guests/dashboard.html
{% extends 'base.html' %}
{% block page_content %}
    <div class="container" id="main">
        <h1>Dashboard</h1>
        <table class="table table-striped">
            <tbody>
            <tr>
                <td>Guests Attending / Possible</td>
                <td>{{ guests }} / {{ possible_guests }}</td>
            </tr>
            <tr>
                <td>Pending Invitations</td>
                <td>{{ pending_invites }} ({{ pending_guests }} guests)</td>
            </tr>
            <tr>
                <td>Unopened Invitations</td>
                <td>{{ unopened_invite_count }}<span class="text-muted"> / {{ total_invites }}</span></td>
            </tr>
            <tr>
                <td>Not Coming</td>
                <td>{{ not_coming_guests }}</td>
            </tr>
            </tbody>
        </table>
        <div class="row">
            <div class="col-lg-6">
                <h1>Guests by category</h1>
                <table class="table">
                    <thead>
                        <tr>
                            {% for category in category_breakdown %}
                            <th>{{ category.party__category }}</th>
                            {% endfor %}
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            {% for category in category_breakdown %}
                            <td>{{ category.count }}</td>
                            {% endfor %}
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="col-lg-6">
                <h1>Meal choices</h1>
                <table class="table">
                    <thead>
                        <tr>
                            {% for meal in meal_breakdown %}
                            <th>{{ meal.meal }}</th>
                            {% endfor %}
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            {% for meal in meal_breakdown %}
                            <td>{{ meal.count }}</td>
                            {% endfor %}
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <h1>Unopened Invitations</h1>
                {% with party_list=parties_with_unopen_invites %}
                    {% include "guests/partials/party_list.html" %}
                {% endwith %}
            </div>
            <div class="col-lg-6">
                <h1>Open Unresponded Invitations</h1>
                {% with parties_with_open_unresponded_invites as party_list %}
                    {% include "guests/partials/party_list.html" %}
                {% endwith %}
            </div>
        </div>
        <div class="col-lg-6">
                <h1>Attending Guests Without Meals</h1>
                {% with guest_list=guests_without_meals %}
                    {% include "guests/partials/guest_list.html" %}
                {% endwith %}
            </div>
        </div>
    </div>
{% endblock %}

guests/templates/guests/invitation.html
{% extends 'base.html' %}
{% load static %}
{% block page_head %}
    <link href="{% static 'bigday/css/invitation.css' %}" rel="stylesheet" xmlns="http://www.w3.org/1999/html">
{% endblock %}
{% block page_content %}
    <div class="container" id="invitation-body">
        <section class="video-container">
            <div class="responsive-video">
                <iframe src="https://www.youtube.com/embed/J_AIs7_Yu5A" frameborder="0" allowfullscreen></iframe>
            </div>
        </section>
        <section class="col-md-6 text-center">
            <div id="invitation-details">
            <h2>Zue and Luk Wedding</h2>
            <p class="lead">
                July 2, 2016, at 4:30 pm<br>
                Ravine Vineyard<br>
                Honey-on-the-moon, ON, KENYA
            </p>
            </div>
        </section>
        <section class="col-md-6">
        <form data-toggle="validator" id="invitation-details" class="form-horizontal" method="post">
            <h2 id="rsvp-header" class="text-center">RSVP</h2>
            <div class="clearfix"></div>
            {% csrf_token %}
            {% for guest in party.ordered_guests.all %}
            <div class="form-group" data-is-child="{{ guest.is_child }}">
                {% with 'attending-'|add:guest.unique_id as attending_label %}
                <label for="{{ attending_label }}" class="col-sm-3 control-label">{{ guest.name }}</label>
                <label class="radio-inline">
                    <input class="attending-radio" type="radio" name="{{ attending_label }}" value="yes" {% if guest.is_attending %}checked="checked"{% endif %} required> will attend
                </label>
                <label class="radio-inline">
                    <input class="attending-radio" type="radio" name="{{ attending_label }}" value="no" {% if guest.is_attending == False %}checked="checked"{% endif %} required> will not attend
                </label>
                {% endwith %}
            </div>
            {% if not guest.is_child %}
            <div class="form-group">
                {% with 'meal-'|add:guest.unique_id as meal_label %}
                <label for="{{ meal_label }}" class="col-sm-3 control-label">... and will eat</label>
                {% for meal_id, meal_name in meals %}
                <label class="radio-inline">
                    <input type="radio" name="{{ meal_label }}" id="{{ meal_label }}-yes" value="{{ meal_id }}" {% if guest.meal == meal_id %}checked="checked"{% endif %} {% if guest.is_attending == False %}disabled{% endif %} required> {{ meal_name }}
                </label>
                {% endfor %}
                {% endwith %}
            </div>
            {% endif %}
            {% endfor %}
            <div class="form-group col-sm-12">
                <input type="text" name="comments" class="form-control" placeholder="Questions/comments/well wishes" >
            </div>
            <div class="form-group">
                <div class="text-center">
                    <input type="submit" class="btn btn-primary" value="Submit Response" />
                </div>
            </div>
        </form>
        </section>
    </div>
{% endblock %}
{% block page_js %}
    <script src="{% static 'validator.js' %}"></script>
    <script>
    $(function () {
        // enable/disable meal choices based on attendance
        $("input.attending-radio").change(function (e) {
            var target = $(e.target);
            if (target.closest('.form-group').data('is-child') === "True") {
                // don't attempt to update meals for children, who don't have them.
                return;
            }
            var value = target.attr('value');
            var mealButtonContainer = target.closest('.form-group').next('.form-group');
            var mealButtons = mealButtonContainer.find('[type=radio]');
            if (value === 'yes') {
                mealButtonContainer.removeClass('text-muted');
                mealButtons.each(function (index, button) {
                    button.disabled = false;
                    button.required = true;
                });
            } else if (value === "no") {
                mealButtonContainer.addClass('text-muted');
                mealButtons.each(function (index, button) {
                    button.checked = false;
                    button.disabled = true;
                    button.required = false;
                });
            }
            // reload validation
            $(document.forms[0]).validator('destroy');
            $(document.forms[0]).validator();
        });
    });
    </script>
{% endblock %}

guests/templates/guests/rsvp_confirmation.html
{% extends 'base.html' %}
{% load static %}
{% block page_head %}
    <link href="{% static 'bigday/css/rsvp-confirmation.css' %}" rel="stylesheet" xmlns="http://www.w3.org/1999/html">
{% endblock %}
{% block page_content %}
    <div class="layer"></div>
    <div class="container" id="main">
        <h2>Hi {{ party.name }}! Thanks for your response!</h2>
        {% if party.any_guests_attending %}
            <p>
                We can't wait to celebrate with you in Kenya!
            </p>
            <p>
                If you've got a minute, you can help us out by filling in a <a href="http://goo.gl/forms/AFszTcpPRW">super quick survey</a> that will help us plan for the most fun and smooth event possible.
                If you have any other questions, don't hesitate to email us at <a href="mailto:{{ support_email }}">{{ support_email }}</a>.
            </p>
        {% else %}
            <p>
                We're sorry you won't be able to join us in Kenya in honeymoon in the moon .
            </p>
            <p>
                We look forward to catching up with you some other time!
            </p>
        {% endif %}
        <p>
            - Cory and Rowena
        </p>
    </div>
{% endblock %}